---
title: "Answering questions"
author: "Happy Beatles"
date: "2020/4/17"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

1.chinamap在哪里下载？<br/>
  答：输入这个命令即可#remotes::install_github("GuangchuangYu/chinamap")

2.刚刚那个v矩阵是怎么构建的？<br/>
  答：这个在synth包中直接输出结果，具体的构建过程比较复杂，可以参考我们在github中的参考文献：Abadie A, Gardeazabal J (2003). “The Economic Costs of Conflict: A Case Study of the Basque Country.” American Economic Review, 93(1), 112–132.

3.请问有没有介绍R语言实现合成控制法的比较详细完整的网页？<br/>
  答：有，在我们的github仓库中有参考文献Abadie, Alberto, Alexis Diamond and Jens Hainmueller. "Synth:An R Package for Synthetic Control Methods in Comparative Case Studies." Journal of Statistical Software, June 2011, Volume 42, Issue 13, p.1-17.

4.疫情准备用什么作为控制组？<br/>
  答：我们准备从疑似病人，人口密度、收治病人医院数等指标选取相似的地区

5.请问各地区政策如何量化度量？<br/>
  答：以确诊人数为结果变量进行政策效果量化。

6.国际疫情数据也可以在nCov2019包中下载吗？<br/>
  答：可以获取国际疫情数据，采用参数'globol'就可以获取全部国外疫情数据。
  
7.疫情地图的动图如何制作？<br/>
  答：可以用plot函数的from和to参数实现 也可以用magick包实现

8.刚刚说绘制省份的疫情地图使用的是世界地图，想问一下莫仓库的地图有国外省份的详细地图吗？<br/>
   答：可以绘制外国的身份地图，但具体的命令我还未学习，但无法将外国省份的疫情数据和nCov2019程序包结合，因为程序包中只有部分外国省份的数据。

9.合成控制法准备使用哪些变量呢？<br/>
  答：结果变量是累计确诊病例，预测变量暂定为疑似病人，人口密度，收治病人医院数，某个时间段的确诊病人，治愈率，死亡率等。
  
10.请问国外的疫情数据是全都有还是只有那10个国家？<br/>
  答：国外的疫情数据可以全部获取，我们做的曲线图中是排序后选取了前十个确诊人数最多的国家。

11.疫情区域特征分析打算从哪几个角度展开分析？<br/>
   答：暂定为不同地区的输入病例规模、疫情发展趋势、防控政策效果以及风险评估。
   
12.绘制中国地图时mapproj包有下载地址吗？<br/>
   答：我在绘制中国地图的时候没用到过mapproj这个包,用的是chinamap.

13.每个地区疫情爆发的起始点有所不同，数据的时间段要怎么选定呢？<br/>
   答：合成控制法也需要满足共同趋势假定，所以我们这选择控制组的合成地区时会考虑选取具有共同趋势的地区，即选择爆发时间点相似的地区。
   
14.国外的疫情数据会具体到每一个省吗？<br/>
   答：目前只有少数几个国家的疫情数据具体到了每个省，剩余的疫情数据都是以国家为单位的。
   
15.做不同城市的快速风险评估时，计划选取哪些指标呢？<br/>
   答：计划选取的指标有：现存确诊病例数，当日新增病例数，本地感染病例数占比（疫情期间该地区累计报告确诊病例数/该地区人口数）， 新增病例均值。

16.怎么保证干预组和控制组无交互影响？<br/>
   答：因为干预组和控制组是属于不同的地区，所以我们认为干预组和控制组之间无交互影响。
